# fly.toml app configuration file generated for soltap-bot-preview on 2024-12-30T21:05:41-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "soltap-bot-preview"
primary_region = "lax"

[build]
  dockerfile = "bot/Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
