[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 200
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
BASE_URL = "https://sol-tap-v2-stable-production.up.railway.app"
TELEGRAM_BOT_TOKEN = "7618469051:AAEvgZv-_qKSUPh6ch1nzeKUDn0DA8wFwFY" 