services:
  - type: web
    name: soltap-v2
    env: node
    plan: free
    buildCommand: |
      npm ci
      npm run build
      ls -la dist/server
      echo "Build completed, checking server file..."
      test -f dist/server/index.js || exit 1
    startCommand: node dist/server/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: true 