# fly.toml app configuration file generated for sol-tap-v2-stable on 2024-12-29T10:35:46-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "soltap-bot"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  DEBUG = "false"
  FRONTEND_URL = "https://soltap.app"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
