name: Backend Pipeline

on:
  push:
    branches: [main, develop]
    paths:
      - 'bot/**'
      - '.github/workflows/backend-pipeline.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'bot/**'

jobs:
  verify:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bot
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./bot/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Type Check
        run: npm run type-check || true

      - name: Lint
        run: npm run lint || true

      - name: Test
        run: npm run test || true

      - name: Build
        run: npm run build
        env:
          NODE_ENV: preview
          PORT: 3000
          DEBUG: true
          TELEGRAM_BOT_TOKEN: test_token
          TELEGRAM_WEBHOOK_URL: http://localhost:3000
          FRONTEND_URL: http://localhost:5173
          DATABASE_URL: test_db_url
          JWT_SECRET: test_secret

  deploy-preview:
    needs: verify
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bot
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install Dependencies
        run: npm ci
          
      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io (Preview)
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          APP_NAME="soltap-bot-preview-${PR_NUMBER}"
          
          # Try to create the app (ignore if it exists)
          flyctl apps create "$APP_NAME" || true
          
          # Deploy the app
          flyctl deploy --app "$APP_NAME" --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const appUrl = `https://soltap-bot-preview-${prNumber}.fly.dev`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🤖 Backend Preview deployed to: ${appUrl}`
            })

  deploy-production:
    needs: verify
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bot
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install Dependencies
        run: npm ci
          
      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io (Production)
        run: flyctl deploy --app soltap-bot --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 