name: Backend Pipeline

on:
  pull_request:
    paths:
      - 'bot/**'
      - '.github/workflows/backend-pipeline.yml'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'bot/package-lock.json'

      - name: Install dependencies
        run: |
          cd bot
          npm ci

      - name: Build
        run: |
          cd bot
          npm run build

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: |
          cd bot
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 