name: Backend Pipeline

on:
  pull_request:
    paths:
      - 'bot/**'
      - '.github/workflows/backend-pipeline.yml'
  push:
    branches: [main]
    paths:
      - 'bot/**'
      - '.github/workflows/backend-pipeline.yml'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd bot
          npm install

      - name: Build
        run: |
          cd bot
          npm run build

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Staging
        if: github.event_name == 'pull_request'
        run: |
          cd bot
          cp fly.staging.toml fly.toml
          flyctl deploy --remote-only --app soltap-bot-preview
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd bot
          flyctl deploy --remote-only --app soltap-bot
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 