name: Bot CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'bot/**'

jobs:
  deploy:
    name: Deploy bot
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./bot

    steps:
      - uses: actions/checkout@v3
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 