name: Bot CD

on:
  push:
    branches: [ main, preview ]
    paths:
      - 'bot/**'

jobs:
  deploy:
    name: Deploy bot
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./bot

    steps:
      - uses: actions/checkout@v3
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly.io
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            flyctl deploy --app sol-tap-v2-stable --remote-only
          else
            flyctl deploy --app sol-tap-staging-bot --remote-only
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 