name: Bot CD

on:
  push:
    branches: [main, preview]
    paths:
      - 'bot/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bot

    steps:
      - uses: actions/checkout@v3
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly.io
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            flyctl deploy --app soltap-bot --remote-only
          else
            flyctl deploy --app soltap-bot-preview --remote-only
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 