name: Backend Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'bot/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'bot/**'

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./bot

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly.io
        run: |
          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
            flyctl deploy --app soltap-bot-preview --remote-only
          else
            flyctl deploy --app soltap-bot --remote-only
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}