name: Game CD

on:
  push:
    branches: [ main, preview ]
    paths:
      - 'game/**'

jobs:
  deploy:
    name: Deploy game
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./game

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Pull Vercel Environment Information
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          fi
      
      - name: Build Project Artifacts
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel build --token=${{ secrets.VERCEL_TOKEN }}
          fi
      
      - name: Deploy Project Artifacts to Vercel
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          fi 