name: Game CI

on:
  push:
    branches: [ develop, main ]
    paths:
      - 'game/**'
  pull_request:
    branches: [ develop, main ]
    paths:
      - 'game/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./game

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './game/package-lock.json'

    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build

    - name: Type check
      run: npm run typecheck

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm test 