name: Game CD

on:
  push:
    branches: [main, preview]
    paths:
      - 'game/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./game
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Pull Vercel Environment Information
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            vercel pull --yes --environment=production --scope=onewordlabs --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel pull --yes --environment=preview --scope=onewordlabs --token=${{ secrets.VERCEL_TOKEN }}
          fi
        
      - name: Build Project Artifacts
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            vercel build --prod --scope=onewordlabs --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel build --scope=onewordlabs --token=${{ secrets.VERCEL_TOKEN }}
          fi
        
      - name: Deploy Project Artifacts to Vercel
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            vercel deploy --prebuilt --prod --scope=onewordlabs --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel deploy --prebuilt --scope=onewordlabs --token=${{ secrets.VERCEL_TOKEN }}
          fi 